<center>Let us consider the fibonnaci matrix.</center>

$$A = \left[ \begin{array}{ccc} 1 & 1 \\ 1 & 0 \\ \end{array} \right] $$
<p></p>
<center> Why is it so?</center>

In [1]:
import numpy as np
A = np.matrix( [[1,1],
               [1, 0]])

In [2]:
print(A**2)

[[2 1]
 [1 1]]


In [3]:
print(A**3)

[[3 2]
 [2 1]]


In [4]:
print(A**4)

[[5 3]
 [3 2]]


In [5]:
print(A**5)

[[8 5]
 [5 3]]


In [6]:
print(A**6)

[[13  8]
 [ 8  5]]


In [7]:
print(A**7)

[[21 13]
 [13  8]]


In [9]:
print(A**8)

[[34 21]
 [21 13]]


<center> And so forth..</center>