In [1]:
import numpy as np

#making a matrix nxn identity matrix

A = np.identity(3)

$$A = \left[ \begin{array}{ccc} 1 & 0 & 0 \\ 0 & 1 & 0\\ 0 & 0 & 1\\ \end{array} \right] $$



In [2]:
print(A)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [10]:
B = np.matrix( [[1,1,3,8,2],
                [8,1,3,3,0],
                [3,2,9,1,0]])

<center> Now let's look at transpose method</center>

In [11]:
print(B)

[[1 1 3 8 2]
 [8 1 3 3 0]
 [3 2 9 1 0]]


In [9]:
print(np.transpose(B))

[[1 8 3]
 [1 1 2]
 [3 3 9]
 [8 3 1]
 [2 0 0]]


$$B = \left[ \begin{array}{ccc} 1 & 1 & 3 & 8 & 2 \\ 8 & 1 & 3 & 3 & 0 \\ 3 & 2 & 9 & 1 & 0\\ \end{array} \right] $$

$$B^T = \left[ \begin{array}{ccc} 1 & 8 & 3 \\ 1 & 1 & 2 \\ 3 & 3 & 9 \\ 8 & 3 & 1 \\ 2 & 0 & 0 \\ \end{array} \right] $$

In [18]:
print(B.T)

[[1 8 3]
 [1 1 2]
 [3 3 9]
 [8 3 1]
 [2 0 0]]


<center> As you can see.</center>
<center> B.T == np.transpose(B)</center>

In [20]:
R = np.matrix( [[1,1],
            [1,0]])