In [2]:
import numpy as np

A = np.matrix( [[3,0,2], [2, 3, 2], [0,5,-1]])
print(A)

[[ 3  0  2]
 [ 2  3  2]
 [ 0  5 -1]]


In [3]:
print(A.np.det)

AttributeError: 'matrix' object has no attribute 'np'